<template>
  <div class="da-border da-rounded-md da-p-6">
    <div
      class="da-font-bold"
    >
      Metric
    </div>
    <div>Period</div>
    <div
      class="da-text-gray-500"
    >
      Site
    </div>
    <div
      class="da-mt-4"
    >
      [chart]
    </div>
  </div>
</template>