name: Build and Deploy Docs and Changelog
env:
  PLUGIN_HANDLE: /analytics/
on:
  push:
    branches:
      - v5-develop
  pull_request:
    branches:
      - v5-develop
jobs:
  build_deploy_docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    strategy:
      fail-fast: true
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - run: cp -vr docs/.vuepress/dist $GITHUB_WORKSPACE
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./dist/
          remote_path: ${{ secrets.PLUGINDOCS_DEPLOY_PATH }}${{ env.PLUGIN_HANDLE }}
          remote_host: ${{ secrets.PLUGINDOCS_DEPLOY_REMOTE_HOST }}
          remote_port: ${{ secrets.PLUGINDOCS_DEPLOY_REMOTE_PORT }}
          remote_user: ${{ secrets.PLUGINDOCS_DEPLOY_REMOTE_USER }}
          remote_key: ${{ secrets.PLUGINDOCS_DEPLOY_PRIVATE_KEY }}
  deploy_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ./CHANGELOG.md
          remote_path: ${{ secrets.PLUGIN_CHANGELOGS_DEPLOY_PATH }}${{ env.PLUGIN_HANDLE }}
          remote_host: ${{ secrets.PLUGINDOCS_DEPLOY_REMOTE_HOST }}
          remote_port: ${{ secrets.PLUGINDOCS_DEPLOY_REMOTE_PORT }}
          remote_user: ${{ secrets.PLUGINDOCS_DEPLOY_REMOTE_USER }}
          remote_key: ${{ secrets.PLUGINDOCS_DEPLOY_PRIVATE_KEY }}
